version: "3.9"
services:
  frontend:
    build:
      context: ./docker/development/frontend
      dockerfile: Dockerfile
      args:
        PACKAGE_JSON: "$PWD/package.json"
    volumes: 
      - ./port-frontend:/app
    ports: 
      - "${EXPOSE_FRONTEND_PORT:-3000}:3000"
    networks: 
      - port-frontend-network
  
  backend:
    env_file: ./docker/development/backend/.env
    restart: unless-stopped
    working_dir: /var/www/
    build: 
      args:
        user: backenduser
        uid: 1000
      context: ./docker/development/backend
      dockerfile: Dockerfile
    volumes: 
      - ./port-backend:/app
    ports: 
      - "${EXPOSE_BACKEND_PORT:-80}:80"
    networks:  
      - port-backend-network
      - port-frontend-network
    
  mysql:
    image: mysql
    env_file: 
      - ./docker/development/mysql/.env
    container_name: port-backend-db
    restart: unless-stopped
    volumes:
      - mysql:/docker-entrypoint-initdb.d
    networks:
      - port-backend-network
    ports: 
      - "${EXPOSE_MYSQL_PORT:-3306}:3306"

networks:
  port-backend-network:
    driver: bridge
  port-frontend-network:
    driver: bridge

volumes:
  mysql: 
